spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/k8?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
#    password: Tang1994!
    password: root
  aop:
    proxy-target-class: true
  http:
    multipart:
      max-request-size: 100Mb
      max-file-size: 100Mb
      enabled: true
server:
  port: 8087

logging:
  config: classpath:logback-spring.xml
  level: debug

#  path:
#  file: D:\var\log\odoo

# ===================================================================
# videojetMarker properties
# ===================================================================

# ===================================================================
# OpcUa properties
# 配置OpcUa订阅节点需注意：
# 1、同一类别对应于一个onDataChange处理事件
# 2、同一设备出现多台，可参考下面格式书写配置，注意缩进，且必须写在类别的最前面，
#    其中NodeBase 为所有节点的共有部分，No为设备编号，SubsribeNode为节点的变量名，No可以不写
# 3、也可以单独配置单一节点
# ===================================================================



opcua:
  retry:
        connBackOffPeriod: 10000
        maxAttempts: 3
        backOffPeriod: 1000
  publishingRate: 100
  plcList:
    - address: opc.tcp://192.168.0.100:4840
      positiveStationOneSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode#  "OPCUA_Product model"[201]
      positiveStationFiveSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[202]
      positiveStationSixSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[203]
      positiveStationSevenSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[204]
    - address: opc.tcp://192.168.0.100:4840
      weldJointStationOneSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[205]
      weldJointStationTwoSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[206]
      oppositeStationOneSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[207]
      oppositeStationTwoSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[208]
    - address: opc.tcp://192.168.0.100:4840
      oppositeStationThreeSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[209]
      oppositeStationFourSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[210]
      oppositeStationFiveSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[211]
      oppositeStationSixSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[212]
    - address: opc.tcp://192.168.0.100:4840
      oppositeStationSevenSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[213]
      oppositeStationEightSubscribeNodes:
        NodeBase# "OPCUA"
          - SubsribeNode# "OPCUA_Product model"[214]
      oppositeStationNineSubscribeNodes:
        NodeBase# "OPCUA"
            - SubsribeNode# "OPCUA_Product model"[215]
      oppositeStationTenSubscribeNodes:
        NodeBase# "OPCUA"
            - SubsribeNode# "OPCUA_Product model"[216]
    - address: opc.tcp://192.168.0.100:4840
      oppositeStationElevenSubscribeNodes:
        NodeBase# "OPCUA"
            - SubsribeNode# "OPCUA_Product model"[193]
      oppositeStationTwelveSubscribeNodes:
        NodeBase# "OPCUA"
            - SubsribeNode# "OPCUA_Product model"[219]
